/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tyroneleyland' at '26/10/16 14:58' with Gradle 2.14
 *
 * @author tyroneleyland, @date 26/10/16 14:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
